apiVersion: 1

datasources:
  - name: CI Metrics PostgreSQL
    uid: ci-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: grafana
    secureJsonData:
      password: grafana
    jsonData:
      database: ci_metrics
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
